//
//  AccountDetailsPresenter.swift
//  ITAU_POC
//
//  Created by Parag on 11/11/19.
//  Copyright (c) 2019 Parag. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AccountDetailsPresentationLogic {
    func presentAccountDetails(response: AccountDetails.AccountData.Response)
    func presentStatementDetails(response: AccountDetails.StatementDetails.Response)
    func presentStartLoaderActivity()
    func presentStopLoaderActivity()
    func presentNetworkError()
}

class AccountDetailsPresenter {
    weak var viewController: AccountDetailsDisplayLogic?
}

extension AccountDetailsPresenter: AccountDetailsPresentationLogic {
    /// Present Account Details VC
    /// - Parameter response: Account Data Response
    func presentAccountDetails(response: AccountDetails.AccountData.Response) {
        let userId = response.accountDetails.userId
        let name = response.accountDetails.name
        let bankAccount = (response.accountDetails.bankAccount ?? "") + " / " + (response.accountDetails.agency ?? "")
        let balance = response.accountDetails.balance
        let agency = response.accountDetails.agency
        let userAccount : UserAccount = UserAccount(userId: userId, name: name, bankAccount: bankAccount, agency: agency, balance: balance)
        let viewModel = AccountDetails.AccountData.ViewModel(accountDetails: userAccount)
        viewController?.displayUserDetail(viewModel: viewModel)
    }
    
    /// Display Account Statements
    /// - Parameter response: Stament List Data
    func presentStatementDetails(response: AccountDetails.StatementDetails.Response) {
        let statementModel = AccountDetails.StatementDetails.ViewModel(statements: response.statements)
        viewController?.displayAccountStatementList(viewModel: statementModel)
    }
    
    /// Start Loading Activity
    func presentStartLoaderActivity() {
        viewController?.startLoaderActivity()
    }
    
    /// Stop Loading Activity
    func presentStopLoaderActivity() {
        viewController?.stopLoaderActivity()
    }
    
    /// Display Network Error
    func presentNetworkError() {
        viewController?.showNetworkError()
        viewController?.stopLoaderActivity()
    }
}
