//
//  AccountDetailsWorker.swift
//  ITAU_POC
//
//  Created by Parag on 11/11/19.
//  Copyright (c) 2019 Parag. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class AccountDetailsWorker {
    func getStatementDetails(urlString : URL, completion: @escaping (Bool, StatementDetailsResponse?, Error?) -> Void) {
        ServiceHandler.getRequest(url: urlString, responseType: StatementDetailsResponse.self) { (statementList, error) in
            if let statementList = statementList {
                completion(true, statementList, nil)
            }
            else {
                completion(false, nil, error)
            }
        }
    }
}
