//
//  LoginPresenter.swift
//  ITAU_POC
//
//  Created by Parag on 11/11/19.
//  Copyright (c) 2019 Parag. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
//Start Here
protocol LoginPresentationLogic {
    func presentAuthenticationResult(response: Login.LoginModel.Response)
    func presentLoggedInUserDetails(request: Login.LoginModel.Request)
    func presentStartLoaderActivity()
    func presentStopLoaderActivity()
}

class LoginPresenter: LoginPresentationLogic {
    weak var viewController: LoginDisplayLogic?
    
    // MARK: Do something
    func presentAuthenticationResult(response: Login.LoginModel.Response) {
        let viewModel = Login.LoginModel.ViewModel(loginResponse: response.loginResponse)
        viewController?.displayAccountDetailsDetails(viewModel: viewModel)
    }
    
    func presentLoggedInUserDetails(request: Login.LoginModel.Request) {
        viewController?.displayLoggedInUserDetails(request: request)
    }
    
    func presentStartLoaderActivity() {
        viewController?.startLoaderActivity()
    }
    
    func presentStopLoaderActivity() {
        viewController?.stopLoaderActivity()
    }
}
