//
//  LoginRouter.swift
//  ITAU_POC
//
//  Created by Parag on 11/11/19.
//  Copyright (c) 2019 Parag. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic {
    func routeToAccountDetails(segue: UIStoryboardSegue?)
}

protocol LoginDataPassing {
    var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginDataPassing {
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?

}

// MARK: LoginRoutingLogic Delegate
extension LoginRouter : LoginRoutingLogic {
    
    /// Route to account Details
    /// - Parameter segue: segue name
    func routeToAccountDetails(segue: UIStoryboardSegue?) {
        if let segue = segue, let destinationVC = segue.destination as? AccountDetailsViewController {
            var destinationDS : AccountDetailsDataStore? = destinationVC.router?.dataStore
            passDataToAccountDetails(source: dataStore, destination: &destinationDS)
        }
        else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            if let destinationVC = storyboard.instantiateViewController(withIdentifier: "AccountDetailsViewController") as? AccountDetailsViewController {
                var destinationDS = destinationVC.router?.dataStore
                passDataToAccountDetails(source: dataStore, destination: &destinationDS)
                navigateToAccountDetails(source: viewController, destination: destinationVC)
            }
        }
    }
    
    // MARK: Navigation
    /// Navigate to account details
    /// - Parameters:
    ///   - source: login VC
    ///   - destination: account detials VC
    func navigateToAccountDetails(source: LoginViewController?, destination: AccountDetailsViewController) {
        source?.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    /// Pass data to account details VC
    /// - Parameters:
    ///   - source: Login VC
    ///   - destination: Account  Details VC
    func passDataToAccountDetails(source: LoginDataStore?, destination: inout AccountDetailsDataStore?) {
        destination?.userDetails = source?.userDetails
    }
}
