//
//  AccountDetailsModels.swift
//  ITAU_POC
//
//  Created by Parag on 11/11/19.
//  Copyright (c) 2019 Parag. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AccountDetails {
    enum AccountData {
        struct Request {
            var user : String?
        }
        struct Response {
            var accountDetails: UserAccount
        }
        struct ViewModel {
            var accountDetails: UserAccount
        }
    }
    
    enum StatementDetails {
        struct Request {
        }
        struct Response {
            var statements: [StatementList]?
        }
        struct ViewModel {
            let statements: [StatementList]?
        }
    }
}

public struct StatementList : Decodable {
    var title: String?
    var desc: String?
    var date: String?
    var value: Double?
}

struct StatementDetailsResponse: Decodable {
    let statementList: [StatementList]
    let error: ErrorModel
}

